In [7]:
import sys
import os
sys.path.append(os.path.abspath(".."))

In [8]:
from Generators.session_generator import generate_sessions
from Generators.User_Generator import get_user

In [16]:
sessions = generate_sessions('user_00001')

In [17]:
sessions

[{'timestamp': '2026-03-17T05:16:24.060709',
  'user_id': 'user_00001',
  'session_id': 'S153328',
  'event_id': 'E00001',
  'page': 'home',
  'event_type': 'page_view',
  'product_id': None,
  'category': None,
  'price': None,
  'quantity': None,
  'device_type': 'mobile',
  'browser': 'Brave_mobile',
  'country': 'India',
  'location': 'Jodhpur',
  'traffic_source': 'email',
  'page_url': '/home',
  'referrer_url': None,
  'time_on_page': 5.686098884254232,
  'cart_value': None,
  'is_purchase': False,
  'ip_address': '123.72.3.211'},
 {'timestamp': '2026-03-17T05:16:58.060709',
  'user_id': 'user_00001',
  'session_id': 'S153328',
  'event_id': 'E00002',
  'page': 'search',
  'event_type': 'search',
  'product_id': None,
  'category': None,
  'price': None,
  'quantity': None,
  'device_type': 'mobile',
  'browser': 'Brave_mobile',
  'country': 'India',
  'location': 'Nagpur',
  'traffic_source': 'email',
  'page_url': '/search',
  'referrer_url': '/home',
  'time_on_page': 51.257770006385975,
  'cart_value': None,
  'is_purchase': False,
  'ip_address': '123.72.3.211'},
 {'timestamp': '2026-03-17T05:17:26.060709',
  'user_id': 'user_00001',
  'session_id': 'S153328',
  'event_id': 'E00005',
  'page': 'product',
  'event_type': 'view_product',
  'product_id': 'H5023',
  'category': 'home',
  'price': 16299,
  'quantity': None,
  'device_type': 'mobile',
  'browser': 'Brave_mobile',
  'country': 'India',
  'location': 'Nashik',
  'traffic_source': 'email',
  'page_url': '/product/H5023',
  'referrer_url': '/search',
  'time_on_page': 23.767970703292413,
  'cart_value': None,
  'is_purchase': False,
  'ip_address': '123.72.3.211'},
 {'timestamp': '2026-03-17T05:17:58.060709',
  'user_id': 'user_00001',
  'session_id': 'S153328',
  'event_id': 'E00009',
  'page': 'wishlist',
  'event_type': 'add_to_wishlist',
  'product_id': None,
  'category': 'home',
  'price': None,
  'quantity': None,
  'device_type': 'mobile',
  'browser': 'Brave_mobile',
  'country': 'India',
  'location': 'Ranchi',
  'traffic_source': 'email',
  'page_url': '/wishlist',
  'referrer_url': '/product/H5023',
  'time_on_page': 47.329939570977004,
  'cart_value': None,
  'is_purchase': False,
  'ip_address': '123.72.3.211'}]

In [18]:
len(sessions)

4

In [19]:
import pandas as pd

In [20]:
df = pd.DataFrame(sessions)

In [21]:
df

,timestamp,user_id,session_id,event_id,page,event_type,product_id,category,price,quantity,...,browser,country,location,traffic_source,page_url,referrer_url,time_on_page,cart_value,is_purchase,ip_address
0,2026-03-17T05:16:24.060709,user_00001,S153328,E00001,home,page_view,NaN,NaN,NaN,None,...,Brave_mobile,India,Jodhpur,email,/home,NaN,5.686099,None,False,123.72.3.211
1,2026-03-17T05:16:58.060709,user_00001,S153328,E00002,search,search,NaN,NaN,NaN,None,...,Brave_mobile,India,Nagpur,email,/search,/home,51.257770,None,False,123.72.3.211
2,2026-03-17T05:17:26.060709,user_00001,S153328,E00005,product,view_product,H5023,home,16299.0,None,...,Brave_mobile,India,Nashik,email,/product/H5023,/search,23.767971,None,False,123.72.3.211
3,2026-03-17T05:17:58.060709,user_00001,S153328,E00009,wishlist,add_to_wishlist,NaN,home,NaN,None,...,Brave_mobile,India,Ranchi,email,/wishlist,/product/H5023,47.329940,None,False,123.72.3.211

In [10]:
sessions = generate_sessions('U1002')

In [11]:
sessions

[{'timestamp': '2026-03-16T04:36:31.862488',
  'user_id': 'U1002',
  'session_id': 'S320190',
  'event_id': 'E00001',
  'page': 'home',
  'event_type': 'page_view',
  'product_id': None,
  'category': None,
  'price': None,
  'quantity': None,
  'device_type': 'mobile',
  'browser': 'Brave_mobile',
  'country': 'Russia',
  'traffic_source': 'organic',
  'page_url': '/home',
  'referrer_url': None,
  'time_on_page': 16.080069684485398,
  'cart_value': None,
  'is_purchase': False},
 {'timestamp': '2026-03-16T04:36:55.862488',
  'user_id': 'U1002',
  'session_id': 'S320190',
  'event_id': 'E00003',
  'page': 'category',
  'event_type': 'browse_category',
  'product_id': None,
  'category': 'books',
  'price': None,
  'quantity': None,
  'device_type': 'mobile',
  'browser': 'Brave_mobile',
  'country': 'Russia',
  'traffic_source': 'organic',
  'page_url': '/category/books',
  'referrer_url': '/home',
  'time_on_page': 9.08384276424459,
  'cart_value': None,
  'is_purchase': False},
 {'timestamp': '2026-03-16T04:37:39.862488',
  'user_id': 'U1002',
  'session_id': 'S320190',
  'event_id': 'E00001',
  'page': 'home',
  'event_type': 'page_view',
  'product_id': None,
  'category': 'books',
  'price': None,
  'quantity': None,
  'device_type': 'mobile',
  'browser': 'Brave_mobile',
  'country': 'Russia',
  'traffic_source': 'organic',
  'page_url': '/home',
  'referrer_url': '/category/books',
  'time_on_page': 55.84415696477604,
  'cart_value': None,
  'is_purchase': False},
 {'timestamp': '2026-03-16T04:37:51.862488',
  'user_id': 'U1002',
  'session_id': 'S320190',
  'event_id': 'E00005',
  'page': 'product',
  'event_type': 'view_product',
  'product_id': 'B3023',
  'category': 'books',
  'price': 1099,
  'quantity': None,
  'device_type': 'mobile',
  'browser': 'Brave_mobile',
  'country': 'Russia',
  'traffic_source': 'organic',
  'page_url': '/product/B3023',
  'referrer_url': '/home',
  'time_on_page': 58.57926650541794,
  'cart_value': None,
  'is_purchase': False},
 {'timestamp': '2026-03-16T04:38:07.862488',
  'user_id': 'U1002',
  'session_id': 'S320190',
  'event_id': 'E00009',
  'page': 'wishlist',
  'event_type': 'add_to_wishlist',
  'product_id': None,
  'category': 'books',
  'price': None,
  'quantity': None,
  'device_type': 'mobile',
  'browser': 'Brave_mobile',
  'country': 'Russia',
  'traffic_source': 'organic',
  'page_url': '/wishlist',
  'referrer_url': '/product/B3023',
  'time_on_page': 8.726115897436035,
  'cart_value': None,
  'is_purchase': False},
 {'timestamp': '2026-03-16T04:38:48.862488',
  'user_id': 'U1002',
  'session_id': 'S320190',
  'event_id': 'E00001',
  'page': 'home',
  'event_type': 'page_view',
  'product_id': None,
  'category': 'books',
  'price': None,
  'quantity': None,
  'device_type': 'mobile',
  'browser': 'Brave_mobile',
  'country': 'Russia',
  'traffic_source': 'organic',
  'page_url': '/home',
  'referrer_url': '/wishlist',
  'time_on_page': 50.32492079965746,
  'cart_value': None,
  'is_purchase': False},
 {'timestamp': '2026-03-16T04:39:21.862488',
  'user_id': 'U1002',
  'session_id': 'S320190',
  'event_id': 'E00001',
  'page': 'deals',
  'event_type': 'page_view',
  'product_id': None,
  'category': 'books',
  'price': None,
  'quantity': None,
  'device_type': 'mobile',
  'browser': 'Brave_mobile',
  'country': 'Russia',
  'traffic_source': 'organic',
  'page_url': '/deals',
  'referrer_url': '/home',
  'time_on_page': 24.335379111770187,
  'cart_value': None,
  'is_purchase': False},
 {'timestamp': '2026-03-16T04:39:48.862488',
  'user_id': 'U1002',
  'session_id': 'S320190',
  'event_id': 'E00001',
  'page': 'home',
  'event_type': 'page_view',
  'product_id': None,
  'category': 'books',
  'price': None,
  'quantity': None,
  'device_type': 'mobile',
  'browser': 'Brave_mobile',
  'country': 'Russia',
  'traffic_source': 'organic',
  'page_url': '/home',
  'referrer_url': '/deals',
  'time_on_page': 7.393164068680103,
  'cart_value': None,
  'is_purchase': False}]

In [11]:
df = pd.DataFrame(sessions)

In [13]:
df.columns

Index(['timestamp', 'user_id', 'session_id', 'event_id', 'page', 'event_type',
       'product_id', 'category', 'price', 'quantity', 'device_type', 'browser',
       'country', 'traffic_source', 'page_url', 'referrer_url', 'time_on_page',
       'cart_value', 'is_purchase'],
      dtype='str')

In [1]:
dict1 = {
    "Name":"Asim"
}

In [2]:
dict1['Name']

'Asim'

In [3]:
dict1.get("Name")

'Asim'

In [13]:
from Generators.User_Generator import user_profiles,get_user

In [15]:
user_profiles['user_00001']['total_orders']+=1

In [14]:
user_profiles

{'user_00001': {'user_id': 'user_00001',
  'age': 41,
  'gender': 'male',
  'country': 'India',
  'signup_date': datetime.datetime(2023, 10, 4, 5, 14, 5, 930765),
  'membership_type': 'prime',
  'total_orders': 0,
  'IPs': {'Primary_IP': '123.72.3.211', 'seconday_ips': ['116.120.177.64']}}}

In [11]:
user_id = get_user()

In [8]:
import pandas as pd

In [9]:
df = pd.DataFrame.from_dict(user_profiles,orient='index')

In [10]:
df

,user_id,age,gender,country,signup_date,membership_type,total_orders
user_00001,user_00001,56,female,India,2026-01-04 10:40:35.295275,normal,0

In [16]:
import random

products = {
    "electronics": [f"E{i}" for i in range(1000,1030)],
    "fashion": [f"F{i}" for i in range(2000,2030)],
    "books": [f"B{i}" for i in range(3000,3030)],
    "sports": [f"S{i}" for i in range(4000,4030)],
    "home": [f"H{i}" for i in range(5000,5030)]
}
BRANDS = {
    "electronics": ["Samsung","Apple","OnePlus","Xiaomi","boAt","Sony","LG","Realme","Lenovo","Noise"],
    "fashion": ["Fabindia","W for Woman","Manyavar","Peter England","Van Heusen","Biba","Raymond","Allen Solly","Aurelia","Jockey"],
    "books": ["Penguin India","Rupa Publications","Westland Books","Harper Collins India","Fingerprint Publishing","Notion Press","Jaico Publishing","Oxford India","Bloomsbury India","Scholastic India"],
    "sports": ["Nivia","Cosco","Vector X","SS Cricket","SG Cricket","Yonex","Adidas India","Nike India","Decathlon","OMTEX"],
    "home": ["Prestige","Bajaj Electricals","Havells","Milton","Cello","Godrej","Nilkamal","Asian Paints","Philips India","Pigeon"]
}
price_ranges = { 
    "electronics": (5000, 80000), 
    "fashion": (300, 5000), 
    "books": (150, 1200), 
    "sports": (500, 15000), 
    "home": (800, 25000) 
}
product_price = {}
for category,product_list in products.items():
    low, high = price_ranges[category]
    for product_id in product_list:
        price = random.randint(low,high)
        price = int(round(price/100)) * 100 - 1
        product_price[product_id] = price
DISCOUNT_RANGES = {
    "electronics": (5, 35),   
    "fashion":     (10, 80),  
    "books":       (10, 40),   
    "sports":      (10, 50),   
    "home":        (5, 60),    
}
def generate_discount(category: str) -> int:
    low, high = DISCOUNT_RANGES[category]
    return random.randint(low, high)


products_details = []
for category in products.keys():
    for product_id in products[category]:
        data = {
            'product_id':product_id,
            'category':category,
            'brand':random.choice(BRANDS[category]),
            'price':product_price.get(product_id),
            'rating':round(random.uniform(2.5, 5.0), 1),
            'stock':random.randint(1000,10000),
            'discount':str(round(generate_discount(category),2))+'%'
        }
        products_details.append(data)

In [18]:
len(products_details)

150

In [20]:
df = pd.DataFrame(products_details)
df

    product_id     category              brand  price  rating  stock discount
0        E1000  electronics              Noise  31899     3.4   9759      34%
1        E1001  electronics             Realme   5699     2.8   4318      16%
2        E1002  electronics             Lenovo   5399     3.2   8269       7%
3        E1003  electronics              Apple  28799     3.7   6969       6%
4        E1004  electronics               boAt  72899     3.6   5488      13%
..         ...          ...                ...    ...     ...    ...      ...
145      H5025         home       Asian Paints  15099     3.0   5398       8%
146      H5026         home       Asian Paints  21499     4.7   7191      44%
147      H5027         home            Havells  22299     3.4   1603      51%
148      H5028         home  Bajaj Electricals   5699     4.3   9165      38%
149      H5029         home      Philips India  19799     4.3   8297       9%

[150 rows x 7 columns]

In [1]:
list1 = [1,2]
list2 = [3,4]

In [3]:
list_new = list1+list2
list_new

[1, 2, 3, 4]

In [4]:
string1 = 'Asim'

In [5]:
list1 = list(string1)
list1

['A', 's', 'i', 'm']

In [ ]:
string1 = '116.72.14.203'

In [ ]:
list2 = ['45.105.88.11']